// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	FoodImageURL   string `json:"foodImageUrl"`
	MediumImageURL string `json:"mediumImageUrl"`
	RecipeCost     string `json:"recipeCost"`
	RecipeID       string `json:"recipeId"`
	RecipeMaterial string `json:"recipeMaterial"`
	RecipeTitle    string `json:"recipeTitle"`
	SmallImageURL  string `json:"smallImageUrl"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RandomRecipe struct {
	FoodImageURL   string `json:"foodImageUrl"`
	MediumImageURL string `json:"mediumImageUrl"`
	RecipeCost     string `json:"recipeCost"`
	RecipeID       string `json:"recipeId"`
	RecipeMaterial string `json:"recipeMaterial"`
	RecipeTitle    string `json:"recipeTitle"`
	SmallImageURL  string `json:"smallImageUrl"`
}
